# Generated by Django 3.0.8 on 2020-08-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="description",
            new_name="project_description",
        ),
    ]
