# Generated by Django 3.0.8 on 2020-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_projects", "0002_auto_20200804_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
