# Generated by Django 3.0.8 on 2020-08-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_projects", "0004_auto_20200807_1618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="project", old_name="project_name", new_name="name",
        ),
    ]
