# Generated by Django 3.1 on 2020-08-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200826_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'post'},
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(blank=True, default='User', null=True),
        ),
    ]
