# Generated by Django 3.1.1 on 2020-09-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0009_auto_20200903_1349"),
        ("blog", "0006_auto_20200903_1349"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="user",),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.profile",
            ),
        ),
    ]
