default:
  ALLOWED_HOSTS: []
  SECRET_KEY: ""
  PORT: 0
  DEBUG: false
  DATABASE_URL: ""

development:
  ALLOWED_HOSTS:
    -localhost
    -127.0.0.1
  SECRET_KEY: "1"
  PORT: 8000
  DEBUG: true
  DATABASE_URL: "postgresql://postgres:1@localhost:5432/tms"

heroku:
  ALLOWED_HOSTS:
    -"yozhikapp.herokuapp.com"
  DEBUG: false