default:
  ALLOWED_HOSTS: []
  SECRET_KEY: ""
  PORT: 0
  DEBUG: false
  DATABASE_URL: ""
  AWS_S3_AVATARS_LOCATION: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""

development:
  AWS_S3_REGION_NAME: "eu-central-1"
  AWS_ACCESS_KEY_ID: "AKIAJX3DIMCUDK7NY3AA"
  AWS_STORAGE_BUCKET_NAME: "w1-project"
  AWS_S3_AVATARS_LOCATION: "avatars-dev"
  SECRET_KEY: "1"
  PORT: 8000
  DEBUG: true
  DATABASE_URL: "postgresql://postgres:1@localhost:5432/tms"

heroku:
  ALLOWED_HOSTS:
    - "yozhikapp.herokuapp.com"
  DEBUG: false
  AWS_S3_REGION_NAME: "eu-central-1"
  AWS_ACCESS_KEY_ID: "AKIAJX3DIMCUDK7NY3AA"
  AWS_STORAGE_BUCKET_NAME: "w1-project"
  AWS_S3_AVATARS_LOCATION: "avatars-heroku"