# Generated by Django 3.0.8 on 2020-08-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats", name="date", field=models.DateTimeField(),
        ),
    ]
