# Generated by Django 3.0.8 on 2020-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='url',
            field=models.TextField(),
        ),
    ]
