# Generated by Django 3.0.8 on 2020-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_auto_20200805_2021"),
    ]

    operations = [
        migrations.AlterModelOptions(name="stats", options={"ordering": ["pk"]},),
        migrations.AddField(
            model_name="stats",
            name="user",
            field=models.TextField(blank=True, null=True),
        ),
    ]
