# Generated by Django 3.0.8 on 2020-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_auto_20200806_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stats",
            name="method",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stats",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
