# Generated by Django 3.0.8 on 2020-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200807_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
