# Generated by Django 3.0.8 on 2020-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_auto_20200807_1623"),
    ]

    operations = [
        migrations.AlterModelOptions(name="stats", options={"ordering": ["-date"]},),
        migrations.AddField(
            model_name="stats",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
