# Generated by Django 3.1 on 2020-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_auto_20200809_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
