# Generated by Django 3.1 on 2020-08-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_auto_20200829_1842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile", options={"verbose_name_plural": "profile"},
        ),
    ]
