# Generated by Django 3.1 on 2020-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
