# Generated by Django 3.1.1 on 2020-09-03 09:15

import django.db.models.deletion
import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_auto_20200831_2056"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="avatar",),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=""
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.profile",
                    ),
                ),
            ],
        ),
    ]
