# Generated by Django 3.1.1 on 2020-09-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_auto_20200903_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="onboarding.profile"
            ),
        ),
    ]
