# Generated by Django 3.1.1 on 2020-09-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_20200903_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'avatar'},
        ),
    ]
